# Generated by Django 5.2.8 on 2025-11-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="default/default.png",
                help_text="Необязательное поле",
                null=True,
                upload_to="users/avatars/",
                verbose_name="Аватар",
            ),
        ),
    ]
