# Generated by Django 5.2.8 on 2025-12-03 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payment_status_payment_stripe_payment_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="status",
        ),
    ]
