# Generated by Django 5.2.8 on 2025-11-13 10:33

import django.db.models.deletion
from django.db import migrations, models

import lms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, unique=True, verbose_name="Наименование курса")),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        default="default/default.png",
                        help_text="Необязательное поле",
                        null=True,
                        upload_to="lms/courses/previews/",
                        verbose_name="Изображение",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание курса")),
            ],
            options={
                "verbose_name": "курс",
                "verbose_name_plural": "курсы",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, unique=True, verbose_name="Наименование урока")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание урока")),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        default="default/default.png",
                        help_text="Необязательное поле",
                        null=True,
                        upload_to="lms/lessons/previews/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "video_link",
                    models.URLField(
                        blank=True,
                        help_text="Необязательное поле",
                        max_length=500,
                        null=True,
                        verbose_name="Ссылка на видео",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата последнего изменения")),
                (
                    "category",
                    models.ForeignKey(
                        default=lms.models.get_default_course,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="lms.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "урок",
                "verbose_name_plural": "уроки",
                "ordering": ["title"],
            },
        ),
    ]
