# Generated by Django 5.2.8 on 2025-11-28 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_coursesubscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursesubscription",
            name="is_active",
        ),
    ]
