# Generated by Django 5.2.8 on 2025-12-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0005_remove_coursesubscription_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=8, verbose_name="Цена курса"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.DecimalField(decimal_places=2, default=500, max_digits=8, verbose_name="Цена урока"),
        ),
    ]
