# Generated by Django 5.2.8 on 2025-12-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0006_course_price_lesson_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
